### PR TITLE
fix type formatting; use built-in abi funcs

### PR DESCRIPTION
**Pull request by jmank88**
This PR attempts to fix some formatting issues (namely we want byte fields to display as `0x` hex), and replaces some of our custom code with equivalent built-in abi funcs along the way, which should stabilize things. If we update that package from geth, we can replace even more of our custom code with newer funcs like `UnpackIntoMap`.

Here it is working on a simple case which printed unreadble bytes before:
```sh
> web3 contract call --abi contracts/GOFS.abi --function owner
0x9fa503A725c92c60bBD7C9006847A3baFc3CaA8d
```

Testing help welcome!

### CODE REVIEW

**Comment by treeder** [comment]
This stopped working:

```sh
web3 contract call --abi Types.abi --function setBytes32 0x9a5c9bf8f8361ca0160821b2ff3d45265ec5b19c4300c880caa13ffc930cb6b9
ERROR: Cannot call the contract: abi: cannot use string as type array as argument
```

And getting the bytes back doesn't look like it's changed either, not seeing the string version:

```sh
web3 contract call --abi Types.abi --function tbytes32
[48 120 57 97 53 99 57 98 102 56 102 56 51 54 49 99 97 48 49 54 48 56 50 49 98 50 102 102 51 100 52 53]
```

**Comment by jmank88** [comment]
Updated. Both of those work for me now.

We still need to convert the _inputs_ to go types, so I restored that. And now we check the output types they give us, and just convert `common.*` types - which get picked up by the Stringer check.

**Comment by treeder** [comment]
I get a different answer back:

```
treeder@penguin:~/dev/gochain/web3/contracts$ web3 contract call --abi Types.abi --function setBytes32 0x9a5c9bf8f8361ca0160821b2ff3d45265ec5b19c4300c880caa13ffc930cb6b9
Transaction address: 0xfdfa0b9ddbc34663dc8961533efda4ae18d53a628f2ef6fb821444ef7332fcde
treeder@penguin:~/dev/gochain/web3/contracts$ web3 contract call --abi Types.abi --function tbytes32
0x3565633562313963343330306338383063616131336666633933306362366239
```

**Comment by jmank88** [comment]
Fixed. We might consider tightening up the input type of `ConvertArguments` to `[]string`, since it is casting them internally anyways.

**Pull request merged**
