### PR TITLE
Added logging transactionHash if a transaction failed + timeout in seconds

### PR DESCRIPTION
**Pull request by devedse**
This PR adds:
* Logging the transactionHash when a transaction fails
* --timeout flag to provide a timeout when waiting for transactions

### CODE REVIEW

**Comment by devedse** [comment]
I'm not sure if this is the right way to do this, but it might be a good start :).

**Review by r-gochain — APPROVED** [review]

**Comment by devedse** [comment]
Seems the build is failing at quite a few places.
I'm not a GO developer at all so I didn't really test anything. 🙂

**Comment by r-gochain** [comment]
I'm fixing

**Comment by devedse** [comment]
Sorry for the oopses :(

**Pull request merged**
