### PR TITLE
EIP155: sign with chainID

### LINKED ISSUE #201: Ability to set chainId in a transaction
Love web3, thanks for making it. It might literally be the only good Linux CLI.

I would love to be able to use Goerli but when I try to talk to Goerli I get
`only replay-protected (EIP-155) transactions allowed over RPC`

A quick Google later it seems like the fix is to set the `chainId` of the transaction. See here
https://ethereum.stackexchange.com/questions/94412/valueerror-code-32000-message-only-replay-protected-eip-155-transac

### PR DESCRIPTION
**Pull request by jmank88**
This change adds `Network.ChainID` for known networks and logic for fetching it for unknown RPC URLs, in order to use with signing transactions more securely with EIP155.

Fixes #201

### CODE REVIEW

**Comment by jmank88** [comment]
Bump for review

**Comment by treeder** [comment]
Any way to make the chainid optional to keep backwards compatability? ie: ask for it before making the call

**Comment by jmank88** [comment]
What do you mean? This code does ask the node for the chain ID if the parameter is nil. If you mean Go API compatibility from adding parameters, that ship sailed a long time ago, and avoiding that mess is what motivated the upcoming Network.* API approach.

**Comment by treeder** [comment]
Yes, I mean this API. How about new functions with the new parameter so we don't break it?  And if it's optional, the current API is simpler anyways.

**Comment by jmank88** [comment]
FWIW It's functionally optional in 99% of cases, but omission comes at the cost of extra rpc calls (per function, so multiple depending on the particular code for the command being executed).

**Comment by jmank88** [comment]
I rigged up the Client to cache the chainID (and it can be preset) so we don't waste any calls and the public API doesn't change. Fortunately all the raw string url cases were internal only.

**Comment by treeder** [comment]
Ahh, good idea.

**Pull request merged**
