### PR TITLE
Reduces gas limit on native transactions to 21000

### PR DESCRIPTION
**Pull request by treeder**

### CODE REVIEW

**Comment by jmank88** [comment]
We raised this last year to accommodate fallback functions:

> This limit was insufficient for sending to a contract with a fallback function.

_Originally posted by @jmank88 in https://github.com/gochain/web3/pull/126#r321694870_

**Comment by treeder** [comment]
Should we let the user decide if they want to raise it?

**Comment by jmank88** [comment]
Sounds good.

**Comment by treeder** [comment]
Updated

**Review by jmank88 — APPROVED** [review]

**Pull request merged**
