### PR TITLE
Upgrading generated contracts to latest OpenZeppelin

### PR DESCRIPTION
**Pull request by treeder**

### CODE REVIEW

**Comment by treeder** [comment]
Getting this error when running `web3 contract build TEST.sol`:

```
Error: Expected ';' but got '{'
   --> <stdin>:452:42:
    |
452 |         (bool success, ) = recipient.call{ value: amount }("");
    |                                          ^

```

**Comment by treeder** [comment]
Should be ready now

**Comment by jmank88** [comment]
It looks like switching to these preset contracts gives up a lot of options. Was there a problem with using the new versions of the token contracts the same way as before?

**Comment by treeder** [comment]
Ya, it does, but this is pretty much the standard now. People can always modify it or write their own contracts if they want something different. 

Also, the old stuff stopped working when I upgraded the compiler so this will be a lot easier for us to maintain.

**Review by jmank88 — APPROVED** [review]
:shrug: I don't totally understand, I thought that they just simplified things by eliminating `ERC20Detailed` and allowing for using `ERC20` directly instead.
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/CHANGELOG.md#breaking-changes-1
https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2161

**Pull request merged**
